#pragma once

enum GfxWarningType : __int32
{                                       // XREF: ?R_WarnOncePerFrame@@YAXW4GfxWarningType@@ZZ/r
    R_WARN_FRONTEND_ENT_LIMIT        = 0x0,
    R_WARN_KNOWN_MODELS              = 0x1,
    R_WARN_KNOWN_SPECIAL_MODELS      = 0x2,
    R_WARN_TEXTURE_OVERRIDES         = 0x3,
    R_WARN_MODEL_LIGHT_CACHE         = 0x4,
    R_WARN_SCENE_ENTITIES            = 0x5,
    R_WARN_TEMP_SKIN_BUF_SIZE        = 0x6,
    R_WARN_MAX_SKINNED_CACHE_VERTICES = 0x7,
    R_WARN_MAX_SCENE_SURFS_SIZE      = 0x8,
    R_WARN_PORTAL_PLANES             = 0x9,
    R_WARN_MAX_CLOUDS                = 0xA,
    R_WARN_MAX_DLIGHTS               = 0xB,
    R_WARN_SMODEL_LIGHTING           = 0xC,
    R_WARN_MAX_DRAWSURFS             = 0xD,
    R_WARN_GFX_CODE_MESH_LIMIT       = 0xE,
    R_WARN_GFX_MARK_MESH_LIMIT       = 0xF,
    R_WARN_MAX_SCENE_DRAWSURFS       = 0x10,
    R_WARN_MAX_FX_DRAWSURFS          = 0x11,
    R_WARN_NONEMISSIVE_FX_MATERIAL   = 0x12,
    R_WARN_NONLIGHTMAP_MARK_MATERIAL = 0x13,
    R_WARN_PRIM_DRAW_SURF_BUFFER_SIZE = 0x14,
    R_WARN_CMDBUF_OVERFLOW           = 0x15,
    R_WARN_MISSING_DECL_NONDEBUG     = 0x16,
    R_WARN_MAX_DYNENT_REFS           = 0x17,
    R_WARN_MAX_SCENE_DOBJ_REFS       = 0x18,
    R_WARN_MAX_SCENE_MODEL_REFS      = 0x19,
    R_WARN_MAX_SCENE_BRUSH_REFS      = 0x1A,
    R_WARN_MAX_CODE_INDS             = 0x1B,
    R_WARN_MAX_CODE_VERTS            = 0x1C,
    R_WARN_MAX_CODE_ARGS             = 0x1D,
    R_WARN_MAX_MARK_INDS             = 0x1E,
    R_WARN_MAX_MARK_VERTS            = 0x1F,
    R_WARN_DEBUG_ALLOC               = 0x20,
    R_WARN_SPOT_LIGHT_LIMIT          = 0x21,
    R_WARN_FX_ELEM_LIMIT             = 0x22,
    R_WARN_VTX_DATA_OVERFLOW         = 0x23,
    R_WARN_WORKER_CMD_SIZE           = 0x24,
    R_WARN_UNKNOWN_STATICMODEL_SHADER = 0x25,
    R_WARN_UNKNOWN_XMODEL_SHADER     = 0x26,
    R_WARN_DYNAMIC_INDEX_BUFFER_SIZE = 0x27,
    R_WARN_MICROCODE_BUFFER_SIZE     = 0x28,
    R_WARN_TOO_MANY_LIGHT_GRID_POINTS = 0x29,
    R_WARN_MAX_FOLIAGE_MODELINFO     = 0x2A,
    R_WARN_MAX_TRANSFER_REQUESTS     = 0x2B,
    R_WARN_MAX_SHADER_CONSTANT_SETS  = 0x2C,
    R_WARN_DYN_SMODEL_MAX_DRAWSTATES = 0x2D,
    R_WARN_MISSING_TECHNIQUE         = 0x2E,
    R_WARN_MARKS_ERR_PROBE_MISMATCH  = 0x2F,
    R_WARN_MARKS_ERR_LMAP_MISMATCH   = 0x30,
    R_WARN_COUNT                     = 0x31,
};

void R_WarnOncePerFrame(GfxWarningType warnType, ...);
double __cdecl R_UpdateFrameRate();
void __cdecl R_WarnInitDvars();
